services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: clariantlandingpagedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: StrongDbPasswordHere@2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file: ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend

volumes:
  postgres_data: