"""track creator of app

Revision ID: 83daeb9de584
Revises: 59162705389d
Create Date: 2025-07-20 09:21:40.869075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83daeb9de584'
down_revision: Union[str, Sequence[str], None] = '59162705389d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'apps', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.drop_column('apps', 'created_by_user_id')
    # ### end Alembic commands ###
