"""Rename port to comment in apps table

Revision ID: b662936e4c54
Revises: 6846dc1dfc7c
Create Date: 2025-07-28 16:26:23.124086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b662936e4c54'
down_revision: Union[str, Sequence[str], None] = '6846dc1dfc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('apps', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('apps', 'comment')
    # ### end Alembic commands ###
